name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['3.13', '3.14', '3.15']

    container: alpine:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v3
      - run:  ./test.sh
