name: CentOS Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['7.5.1804', '8.4.2105']

    container: centos:${{ matrix.tag }}

    steps:
      - run: yum -y update && yum -y install git
        if:  ${{ matrix.tag == '7.5.1804' }}

        # https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist
      - run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
          dnf -y update
          dnf -y install git
        if:  ${{ matrix.tag == '8.4.2105' }}

      - uses: actions/checkout@v3
      - run:  test.sh
