name: Debian GNU/Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['9.13', '10.7', '11.3']

    container: debian:${{ matrix.tag }}

    steps:
      - run: apt -y update
      - run: apt -y install git

      - uses: actions/checkout@v3
      - run: test.sh
