name: Manjaro Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: zelec/manjarolinux

    steps:
      - run: pacman -Syyuu --noconfirm
      - run: pacman -S     --noconfirm git

      - uses: actions/checkout@v3

      - run: test.sh
