name: openSUSE Leap

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [15.1, 15.2, 15.3, 15.4]

    container: opensuse/leap:${{ matrix.tag }}

    steps:
      - run: zypper update  -y
      - run: zypper install -y git tar xz

      - uses: actions/checkout@v3

      - run: ./test.sh
