name: VoidLinux-glibc

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: voidlinux/voidlinux

    steps:
      - run: xbps-install -u xbps
      - run: xbps-install -Syu git xz

      - uses: actions/checkout@v3

      - run: ./test.sh
